// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { Boss } from "./boss_type";
import { Guilds as __Guilds } from "./guilds_type";

import { EventContext, Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `boss`.
 *
 * Obtain a handle from the [`boss`] property on [`RemoteTables`],
 * like `ctx.db.boss`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.boss.on_insert(...)`.
 */
export class BossTableHandle {
  tableCache: TableCache<Boss>;

  constructor(tableCache: TableCache<Boss>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<Boss> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `identity` unique index on the table `boss`,
   * which allows point queries on the field of the same name
   * via the [`BossIdentityUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.boss.identity().find(...)`.
   *
   * Get a handle on the `identity` unique index on the table `boss`.
   */
  identity = {
    // Find the subscribed row whose `identity` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: Identity): Boss | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.identity, col_val)) {
          return row;
        }
      }
    },
  };
  /**
   * Access to the `turnPosition` unique index on the table `boss`,
   * which allows point queries on the field of the same name
   * via the [`BossTurnPositionUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.boss.turnPosition().find(...)`.
   *
   * Get a handle on the `turnPosition` unique index on the table `boss`.
   */
  turnPosition = {
    // Find the subscribed row whose `turnPosition` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: number): Boss | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.turnPosition, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: Boss) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: Boss) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: Boss) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: Boss) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: Boss, newRow: Boss) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: Boss, newRow: Boss) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
