// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
export type GameSecrets = {
  gameToken: bigint,
  host: Identity,
  startTime: Timestamp,
  currentTurnPosition: number | undefined,
  isActive: boolean,
  hasStarted: boolean,
};

/**
 * A namespace for generated helper functions.
 */
export namespace GameSecrets {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("gameToken", AlgebraicType.createU64Type()),
      new ProductTypeElement("host", AlgebraicType.createIdentityType()),
      new ProductTypeElement("startTime", AlgebraicType.createTimestampType()),
      new ProductTypeElement("currentTurnPosition", AlgebraicType.createOptionType(AlgebraicType.createU8Type())),
      new ProductTypeElement("isActive", AlgebraicType.createBoolType()),
      new ProductTypeElement("hasStarted", AlgebraicType.createBoolType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: GameSecrets): void {
    GameSecrets.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): GameSecrets {
    return GameSecrets.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


