// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { GameSecrets } from "./game_secrets_type";
import { EventContext, Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `game_secrets`.
 *
 * Obtain a handle from the [`gameSecrets`] property on [`RemoteTables`],
 * like `ctx.db.gameSecrets`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.gameSecrets.on_insert(...)`.
 */
export class GameSecretsTableHandle {
  tableCache: TableCache<GameSecrets>;

  constructor(tableCache: TableCache<GameSecrets>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<GameSecrets> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `gameToken` unique index on the table `game_secrets`,
   * which allows point queries on the field of the same name
   * via the [`GameSecretsGameTokenUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.gameSecrets.gameToken().find(...)`.
   *
   * Get a handle on the `gameToken` unique index on the table `game_secrets`.
   */
  gameToken = {
    // Find the subscribed row whose `gameToken` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: bigint): GameSecrets | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.gameToken, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: GameSecrets) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: GameSecrets) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: GameSecrets) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: GameSecrets) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: GameSecrets, newRow: GameSecrets) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: GameSecrets, newRow: GameSecrets) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
