// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { Guilds as __Guilds } from "./guilds_type";

export type Guild = {
  guildToken: bigint,
  gameToken: bigint,
  representative: __Guilds,
  x: number,
  y: number,
};

/**
 * A namespace for generated helper functions.
 */
export namespace Guild {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("guildToken", AlgebraicType.createU64Type()),
      new ProductTypeElement("gameToken", AlgebraicType.createU64Type()),
      new ProductTypeElement("representative", __Guilds.getTypeScriptAlgebraicType()),
      new ProductTypeElement("x", AlgebraicType.createU8Type()),
      new ProductTypeElement("y", AlgebraicType.createU8Type()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: Guild): void {
    Guild.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): Guild {
    return Guild.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


