// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { LobbySecret } from "./lobby_secret_type";
import { EventContext, Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `lobby_secret`.
 *
 * Obtain a handle from the [`lobbySecret`] property on [`RemoteTables`],
 * like `ctx.db.lobbySecret`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.lobbySecret.on_insert(...)`.
 */
export class LobbySecretTableHandle {
  tableCache: TableCache<LobbySecret>;

  constructor(tableCache: TableCache<LobbySecret>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<LobbySecret> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `lobbyToken` unique index on the table `lobby_secret`,
   * which allows point queries on the field of the same name
   * via the [`LobbySecretLobbyTokenUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.lobbySecret.lobbyToken().find(...)`.
   *
   * Get a handle on the `lobbyToken` unique index on the table `lobby_secret`.
   */
  lobbyToken = {
    // Find the subscribed row whose `lobbyToken` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: bigint): LobbySecret | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.lobbyToken, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: LobbySecret) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: LobbySecret) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: LobbySecret) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: LobbySecret) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: LobbySecret, newRow: LobbySecret) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: LobbySecret, newRow: LobbySecret) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
